frr version 8.4
frr defaults traditional
hostname as4_r2
service integrated-vtysh-config
!
interface lo
 ipv6 ospf6 area 0.0.0.0
 ipv6 ospf6 passive
!
interface eth0
!
interface eth1
!
interface eth2
 ipv6 ospf6 area 0.0.0.0
!
router ospf6
 router-id 2.2.2.2
!
router bgp 4
 bgp router-id 2.2.2.2
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 neighbor 2001:db8:25::2 remote-as 1
 neighbor 2001:db8:2d::2 remote-as 2
 neighbor 2001:db8:1::3 remote-as 4
 neighbor 2001:db8:1::3 update-source lo
 !
 address-family ipv6 unicast
  network 2001:db8:1::2/128
  neighbor 2001:db8:25::2 activate
  neighbor 2001:db8:2d::2 activate
  neighbor 2001:db8:1::3 activate
  neighbor 2001:db8:1::3 next-hop-self
 exit-address-family
!

line vty
!
