
frr version 8.4
frr defaults traditional
hostname r1
service integrated-vtysh-config
!

interface lo
!

interface eth0
!

router bgp 2
 bgp router-id 1.1.1.1
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast


 neighbor 2001:db8:12::2 remote-as 1


 !
 address-family ipv6 unicast

  network 2001:db8:1::1/128



  neighbor 2001:db8:12::2 activate



 exit-address-family
!
line vty
