frr version 8.4
frr defaults traditional

log file /tmp/frr.log
!debug zebra mpls detailed
!debug isis sr-events
!debug zebra packet
hostname r2
service integrated-vtysh-config
!

!
interface lo
 ipv6 router isis CORE
 ip address 2.2.2.2/32
 ipv6 address 3fff:100::2/128
 isis passive
!
interface eth0
 ipv6 router isis CORE
 isis circuit-type level-1
 isis network point-to-point
 isis bfd
 isis hello-interval 3
 isis metric 10 level-1
 isis fast-reroute ti-lfa node-protection link-fallback
!
interface eth1
 ipv6 router isis CORE
 isis circuit-type level-1
 isis network point-to-point
 isis bfd
 isis hello-interval 3
 isis metric 10 level-1
 isis fast-reroute ti-lfa node-protection link-fallback
!
router isis CORE
 net 49.0001.0000.0000.0002.00
 is-type level-1
 metric-style wide
 lsp-gen-interval 5
 segment-routing on
 segment-routing global-block 16000 23999
 segment-routing local-block 15000 15999
 segment-routing prefix 3fff:100::2/128 index 2
 segment-routing node-msd 8
!

line vty
!
