
frr version 8.4
frr defaults traditional
hostname r6
service integrated-vtysh-config
!

interface lo
!

interface eth0
!

router bgp 4
 bgp router-id 6.6.6.6
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast


 neighbor 2001:db8:46::1 remote-as 1


 !
 address-family ipv6 unicast

  network 2001:db8:1::6/128



  neighbor 2001:db8:46::1 activate



 exit-address-family
!
line vty
