frr version 8.4
frr defaults traditional
hostname as1
service integrated-vtysh-config
!
interface lo
!
interface eth0
!
interface eth1
!
interface eth2
!

router bgp 1
 bgp router-id 1.1.1.1
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
! BGP Roles (RFC 9234)
 neighbor 2001:db8:fdc3::2 remote-as 2
 neighbor 2001:db8:fdc3::2 local-role peer strict-mode
 neighbor 2001:db8:33bc::2 remote-as 3
 neighbor 2001:db8:33bc::2 local-role provider strict-mode
 neighbor 2001:db8:70f5::2 remote-as 4
 neighbor 2001:db8:70f5::2 local-role provider strict-mode
!
address-family ipv6 unicast
 network 2001:db8:1::1/128
 neighbor 2001:db8:fdc3::2 activate
 neighbor 2001:db8:fdc3::2 route-map LP_as2 in
 neighbor 2001:db8:33bc::2 activate
 neighbor 2001:db8:33bc::2 route-map LP_as3 in
 neighbor 2001:db8:70f5::2 activate
 neighbor 2001:db8:70f5::2 route-map LP_as4 in
exit-address-family
!
route-map LP_as2 permit 10
 set local-preference 100
!
route-map LP_as3 permit 10
 set local-preference 200
!
route-map LP_as4 permit 10
 set local-preference 200
!
line vty
