frr version 8.4
frr defaults traditional
hostname as1_r5
service integrated-vtysh-config
!
interface lo
 ipv6 ospf6 area 0.0.0.0
 ipv6 ospf6 passive
!
interface eth0
!
interface eth1
 ipv6 ospf6 area 0.0.0.0
!
interface eth2
 ipv6 ospf6 area 0.0.0.0
!
router ospf6
 router-id 5.5.5.5
!
router bgp 1
 bgp router-id 5.5.5.5
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 neighbor 2001:db8:25::1 remote-as 4
 neighbor 2001:db8:1::1 remote-as 1
 neighbor 2001:db8:1::1 update-source lo
 neighbor 2001:db8:1::4 remote-as 1
 neighbor 2001:db8:1::4 update-source lo
 neighbor 2001:db8:1::6 remote-as 1
 neighbor 2001:db8:1::6 update-source lo
 !
 address-family ipv6 unicast
  network 2001:db8:1::5/128
  neighbor 2001:db8:25::1 activate
  neighbor 2001:db8:1::1 activate
  neighbor 2001:db8:1::1 next-hop-self
  neighbor 2001:db8:1::4 activate
  neighbor 2001:db8:1::4 next-hop-self
  neighbor 2001:db8:1::6 activate
  neighbor 2001:db8:1::6 next-hop-self
 exit-address-family
!

line vty
!
