LAB_DESCRIPTION="BGP Local Preference Lab"
LAB_AUTHOR="Noah Van Horenbeke"
LAB_NAME="bgp_ipv6_local_pref"



as1[image]="kathara/frr"
as1[ipv6]="true"
as1[0]="A"   # to as2
as1[1]="B"   # to as3
as1[2]="C"   # to as4

as2[image]="kathara/frr"
as2[ipv6]="true"
as2[0]="A"   # to as1
as2[1]="D"   # to as4

as3[image]="kathara/frr"
as3[ipv6]="true"
as3[0]="B"   # to as1
as3[1]="E"   # to as4

as4[image]="kathara/frr"
as4[ipv6]="true"
as4[0]="C"   # to as1
as4[1]="D"   # to as2
as4[2]="E"   # to as3
as4[3]="F"   # to as7

as7[image]="kathara/frr"
as7[ipv6]="true"
as7[0]="F"   # to as4