LAB_NAME="bgp_anycast_dns_simple"
LAB_AUTHOR="Noah Van Horenbeke"


as1_r1[ipv6]="true"
as1_r1[0]="A"
as1_r1[1]="B"
as1_r1[2]="F"
as1_r1[image]="kathara/frr:latest"


as2_r2[ipv6]="true"
as2_r2[0]="A"
as2_r2[1]="C"
as2_r2[image]="kathara/frr:latest"

as100_ns1[ipv6]="true"
as100_ns1[0]="C"
as100_ns1[image]="noahvanh1315/frr-bind9:latest"


as3_r3[ipv6]="true"
as3_r3[0]="B"
as3_r3[1]="E"
as3_r3[image]="kathara/frr:latest"

as4_r4[ipv6]="true"
as4_r4[0]="E"
as4_r4[1]="D"
as4_r4[image]="kathara/frr:latest"

as200_ns2[ipv6]="true"
as200_ns2[0]="D"
as200_ns2[image]="noahvanh1315/frr-bind9:latest"


client[ipv6]="true"
client[0]="F"
client[image]="kathara/base:latest"

