frr version 8.4
frr defaults traditional
hostname r3
service integrated-vtysh-config
!
interface lo
 ipv6 ospf6 area 0.0.0.0
 ipv6 ospf6 passive
!
interface eth0
 ipv6 ospf6 area 0.0.0.0
 ipv6 ospf6 cost 10
 ipv6 ospf6 ifmtu 1480
!
interface eth1
 ipv6 ospf6 area 0.0.0.0
 ipv6 ospf6 cost 10
 ipv6 ospf6 ifmtu 1460
!
router ospf6
 router-id 3.3.3.3
!

line vty
!
