
frr version 8.4
frr defaults traditional
hostname as5_r9
service integrated-vtysh-config
!
interface lo
!
interface eth0
!
interface eth1
!
router bgp 5
 bgp router-id 9.9.9.9
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 neighbor 2001:db8:89::1 remote-as 3
 neighbor 2001:db8:9d::2 remote-as 2
 !
 address-family ipv6 unicast
  network 2001:db8:1::9/128
  neighbor 2001:db8:89::1 activate
  neighbor 2001:db8:9d::2 activate
 exit-address-family
!
line vty
