LAB_DESCRIPTION="A network showing the operation of the OSPFv6 routing protocol with a single area"
LAB_NAME="ospf_single_area_lab"
LAB_AUTHOR="T. Caiazzi, G. Di Battista, M. Rimondini, M. Patrignani, adapted by Noah Van Horenbeke"
LAB_EMAIL=contact@kathara.org
LAB_WEB=http://www.kathara.org/


r1[0]="A"
r1[1]="C"
r1[image]="kathara/frr"
r1[ipv6]="true"

r2[0]="A"
r2[1]="D"
r2[image]="kathara/frr"
r2[ipv6]="true"

r3[0]="A"
r3[1]="B"
r3[image]="kathara/frr"
r3[ipv6]="true"

r4[0]="B"
r4[1]="C"
r4[image]="kathara/frr"
r4[ipv6]="true"

r5[0]="C"
r5[1]="D"
r5[image]="kathara/frr"
r5[ipv6]="true"