LAB_NAME="fastreroute_tilfa_lab"

r1[ipv6]="true"
r1[0]="A"
r1[1]="D"
r1[2]="C"
r1[image]="kathara/frr:latest"

r2[ipv6]="true"
r2[0]="E"
r2[1]="D"
r2[image]="kathara/frr:latest"

r3[ipv6]="true"
r3[0]="F"
r3[1]="E"
r3[2]="K"
r3[image]="kathara/frr:latest"

r4[ipv6]="true"
r4[0]="L"
r4[1]="G"
r4[2]="C"
r4[3]="I"
r4[image]="kathara/frr:latest"

r5[ipv6]="true"
r5[0]="A"
r5[1]="G"
r5[image]="kathara/frr:latest"

r6[ipv6]="true"
r6[0]="J"
r6[1]="H"
r6[2]="K"
r6[3]="I"
r6[image]="kathara/frr:latest"

r7[ipv6]="true"
r7[0]="L"
r7[1]="J"
r7[image]="kathara/frr:latest"

r8[ipv6]="true"
r8[0]="F"
r8[1]="H"
r8[image]="kathara/frr:latest"