LAB_NAME="scapyLab"
LAB_DESCRIPTION="Scapy scanning and DNS reflection lab"
LAB_AUTHOR="Noah Van Horenbeke"

# =========================
# NETWORK
# =========================

attacker[0]="A"
target[0]="A"
dns[0]="A"
monitor[0]="A"

# =========================
# IMAGES
# =========================

attacker[image]="kathara/base"
target[image]="kathara/base"
dns[image]="kathara/dnsmasq"
monitor[image]="kathara/base"