frr version 8.4
frr defaults traditional
hostname as2
service integrated-vtysh-config
!
interface lo
!
interface eth0
!
interface eth1
!

router bgp 2
 bgp router-id 2.2.2.2
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
! BGP Roles (RFC 9234)
 neighbor 2001:db8:fdc3::1 remote-as 1
 neighbor 2001:db8:fdc3::1 local-role peer strict-mode
 neighbor 2001:db8:65d7::2 remote-as 4
 neighbor 2001:db8:65d7::2 local-role provider strict-mode
!
address-family ipv6 unicast
 network 2001:db8:1::2/128
 neighbor 2001:db8:fdc3::1 activate
 neighbor 2001:db8:fdc3::1 route-map LP_as1 in
 neighbor 2001:db8:65d7::2 activate
 neighbor 2001:db8:65d7::2 route-map LP_as4 in
exit-address-family
!
route-map LP_as1 permit 10
 set local-preference 100
!
route-map LP_as4 permit 10
 set local-preference 200
!
line vty
