LAB_NAME="bgp_iBGP_ipv6_lab"

LAB_AUTHOR="Noah Van Horenbeke"
as1_r1[ipv6]="true"
as1_r1[0]="A"
as1_r1[1]="G"
as1_r1[2]="H"
as1_r1[image]="kathara/frr"

as4_r2[ipv6]="true"
as4_r2[0]="B"
as4_r2[1]="F"
as4_r2[2]="K"
as4_r2[image]="kathara/frr"

as4_r3[ipv6]="true"
as4_r3[0]="C"
as4_r3[1]="K"
as4_r3[image]="kathara/frr"

as1_r4[ipv6]="true"
as1_r4[0]="C"
as1_r4[1]="G"
as1_r4[2]="J"
as1_r4[image]="kathara/frr"

as1_r5[ipv6]="true"
as1_r5[0]="B"
as1_r5[1]="I"
as1_r5[2]="J"
as1_r5[image]="kathara/frr"

as1_r6[ipv6]="true"
as1_r6[0]="H"
as1_r6[1]="I"
as1_r6[image]="kathara/frr"

as3_r8[ipv6]="true"
as3_r8[0]="A"
as3_r8[1]="D"
as3_r8[image]="kathara/frr"

as5_r9[ipv6]="true"
as5_r9[0]="D"
as5_r9[1]="E"
as5_r9[image]="kathara/frr"

as2_d1[ipv6]="true"
as2_d1[0]="E"
as2_d1[1]="F"
as2_d1[image]="kathara/frr"

