frr version 8.4
frr defaults traditional
hostname as3
service integrated-vtysh-config
!
interface lo
!
interface eth0
!
interface eth1
!
! --- COMMUNITY LISTS ---
bgp community-list standard CUSTOMER permit 100:1
bgp community-list standard PEER permit 100:2
bgp community-list standard PROVIDER permit 100:3
!
ipv6 prefix-list OWN_PREFIX seq 10 permit 2001:db8:1::3/128
!
router bgp 3
 bgp router-id 3.3.3.3
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 neighbor 2001:db8:33bc::1 remote-as 1
 neighbor 2001:db8:37fb::2 remote-as 4
 !
 address-family ipv6 unicast
  network 2001:db8:1::3/128
  neighbor 2001:db8:33bc::1 activate
  neighbor 2001:db8:33bc::1 route-map LP_as1 in
  neighbor 2001:db8:33bc::1 route-map EXPORT_PROVIDER out
  neighbor 2001:db8:37fb::2 activate
  neighbor 2001:db8:37fb::2 route-map LP_as4 in
  neighbor 2001:db8:37fb::2 route-map EXPORT_PEER out
 exit-address-family
!


route-map EXPORT_PEER permit 10
 match ipv6 address prefix-list OWN_PREFIX
!
route-map EXPORT_PEER permit 20
 match community CUSTOMER
!
route-map EXPORT_PROVIDER permit 10
 match ipv6 address prefix-list OWN_PREFIX
!
route-map EXPORT_PROVIDER permit 20
 match community CUSTOMER
!

route-map LP_as1 permit 10
 set local-preference 50
 set community 100:3 additive
!
route-map LP_as4 permit 10
 set local-preference 100
 set community 100:2 additive
!
line vty
