frr version 8.4
frr defaults traditional
hostname as1
service integrated-vtysh-config
!
interface lo
!
interface eth0
!
interface eth1
!
interface eth2
!
! --- COMMUNITY LISTS ---
bgp community-list standard CUSTOMER permit 100:1
bgp community-list standard PEER permit 100:2
bgp community-list standard PROVIDER permit 100:3
!
ipv6 prefix-list OWN_PREFIX seq 10 permit 2001:db8:1::1/128
!
router bgp 1
 bgp router-id 1.1.1.1
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 neighbor 2001:db8:fdc3::2 remote-as 2
 neighbor 2001:db8:33bc::2 remote-as 3
 neighbor 2001:db8:70f5::2 remote-as 4
 !
 address-family ipv6 unicast
  network 2001:db8:1::1/128
  neighbor 2001:db8:fdc3::2 activate
  neighbor 2001:db8:fdc3::2 route-map LP_as2 in
  neighbor 2001:db8:fdc3::2 route-map EXPORT_PEER out
  neighbor 2001:db8:33bc::2 activate
  neighbor 2001:db8:33bc::2 route-map LP_as3 in
  neighbor 2001:db8:33bc::2 route-map EXPORT_CUSTOMER out
  neighbor 2001:db8:70f5::2 activate
  neighbor 2001:db8:70f5::2 route-map LP_as4 in
  neighbor 2001:db8:70f5::2 route-map EXPORT_CUSTOMER out
 exit-address-family
!


route-map EXPORT_CUSTOMER permit 10
!
route-map EXPORT_PEER permit 10
 match ipv6 address prefix-list OWN_PREFIX
!
route-map EXPORT_PEER permit 20
 match community CUSTOMER
!

route-map LP_as2 permit 10
 set local-preference 100
 set community 100:2 additive
!
route-map LP_as3 permit 10
 set local-preference 200
 set community 100:1 additive
!
route-map LP_as4 permit 10
 set local-preference 200
 set community 100:1 additive
!
line vty
