frr version 8.4
frr defaults traditional
hostname as7
service integrated-vtysh-config
!
interface lo
!
interface eth0
!
! --- COMMUNITY LISTS ---
bgp community-list standard CUSTOMER permit 100:1
bgp community-list standard PEER permit 100:2
bgp community-list standard PROVIDER permit 100:3
!
ipv6 prefix-list OWN_PREFIX seq 10 permit 2001:db8:1::7/128
!
router bgp 7
 bgp router-id 7.7.7.7
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 neighbor 2001:db8:650d::1 remote-as 4
 !
 address-family ipv6 unicast
  network 2001:db8:1::7/128
  neighbor 2001:db8:650d::1 activate
  neighbor 2001:db8:650d::1 route-map LP_as4 in
  neighbor 2001:db8:650d::1 route-map EXPORT_PROVIDER out
 exit-address-family
!


route-map EXPORT_PROVIDER permit 10
 match ipv6 address prefix-list OWN_PREFIX
!
route-map EXPORT_PROVIDER permit 20
 match community CUSTOMER
!

route-map LP_as4 permit 10
 set local-preference 50
 set community 100:3 additive
!
line vty
