
frr version 8.4
frr defaults traditional
hostname as2_d1
service integrated-vtysh-config
!
interface lo
!
interface eth0
!
interface eth1
!
router bgp 2
 bgp router-id 10.10.10.10
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 neighbor 2001:db8:9d::1 remote-as 5
 neighbor 2001:db8:2d::1 remote-as 4
 !
 address-family ipv6 unicast
  network 2001:db8:1::10/128
  neighbor 2001:db8:9d::1 activate
  neighbor 2001:db8:2d::1 activate
 exit-address-family
!
line vty
